Additional error checking; standardized header; looking only for debian-specific files.

diff --git a/raptr-add b/raptr-add
--- a/raptr-add
+++ b/raptr-add
@@ -1,17 +1,29 @@
-#!/usr/bin/env bash -e
+#!/usr/bin/env bash
+set -ex
 script_name="$(basename "$BASH_SOURCE")"
 script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
 while [[ $# > 1 ]]; do
   key="$1"; shift
   case $key in
-    -n|--name) name="$1"; shift  ;;
-    -p|--packages) packages="$1"; shift  ;;
+    -s|--section) section="$1"; shift ;;
+    -n|--name) name="$1"; shift ;;
+    -d|--directory) directory="$1"; shift ;;
     *);;
   esac
 done
 
-[ -z "$name" ] && echo "Missing required package name." && exit 1
-[ -z "$packages" ] && echo "Missing required directory of packages." && exit 1
+[ -z "$section" ] && echo "Missing required name of section to which package should be added." && exit 1
+[ -z "$name" ] && echo "Missing required name of package to add." && exit 1
+[ -z "$directory" ] && echo "Missing required directory of packages to add." && exit 1
+[ ! -d "pool/$section" ] && echo "The section specified does not exist." && exit 1
+[ ! -d "$directory" ] && echo "The directory specified was not found." && exit 1
+[[ "$name" =~ ( |\') ]] && echo "The package name cannot contain whitespace characters." && exit 1
+
+# what about bz, lzma, xz?
+files=$(ls "$directory/"*.{deb,dsc,debian.tar.gz,diff.gz,orig.tar.gz,deb-control,dsc-cached} 2> /dev/null || true)
+[ -z "$files" ] && echo "No package files found." && exit 1
+
+mkdir -p "pool/$section/${name::1}/$name"
 
 exit 0
