Pushing everything into fuctions.

diff --git a/raptr-add b/raptr-add
--- a/raptr-add
+++ b/raptr-add
@@ -3,85 +3,114 @@ set -e
 script_name="$(basename "$BASH_SOURCE")"
 script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
-function parse_arguments() {
-	while [[ "$#" > 0 ]]; do
-	  case "$1" in
-	    -t|--target|--target=) target="$2"; shift ;; # TODO: allow multiple targets
-	    -p|--package|--package=) package="$2"; shift ;;
+while [[ "$#" > 0 ]]; do
+	case "$1" in
+		-t|--target|--target=) raw_target="$2"; shift ;; # TODO: allow multiple targets
+		-p|--package|--package=) raw_package="$2"; shift ;;
 		*) shift ;;
-	  esac
-	done
-}
+	esac
+done
+
 function assert_working_directory() {
-	[ ! -d ./dists ] && echo "The command must be executed inside of an active repository." && return 1
-	[ ! -d ./pool ] && echo "The command must be executed inside of an active repository." && return 1
+	[ ! -d ./dists ] && echo "The command must be executed inside of an active repository." >&2 && return 1
+	[ ! -d ./pool ] && echo "The command must be executed inside of an active repository." >&2 && return 1
+	return 0
 }
 function assert_arguments() {
-	[ -z "${target}" ] && echo "Missing required target to which package should be added." && return 1
-	[ -z "${package}" ] && echo "Missing required package to add." && return 1
+	[ -z "$1" ] && echo "Missing required target to which package should be added." >&2 && return 1
+	[ -z "$2" ] && echo "Missing required package to add." >&2 && return 1
+	return 0
 }
 function expand_target() {
-	local target_argument="$1"
 	local available_targets="$(cd dists; find . -mindepth 2 -maxdepth 2 -type d | \
 		sed -r 's/\.\/(.*?)/\1 /g' | tr '\n' ' ')"
-	local available_archives="$(cd dists; ls -d * | tr '\n' ' ')"
-	local available_sections="$(cd pool; ls -d * | tr '\n' ' ' )"
-	local discovered=""
+	local target_input="$1"
 
 	# TODO: avoid * expansion but allow looping (use IFS?)
-	for t in "${target_argument}"; do
-		if [ "${t}" == "*/*" ] || [ "${t}" == "*" ]; then local discovered="${available_targets}"
-		elif [[ " ${available_targets} " == *" ${t} "* ]]; then local discovered="${discovered} ${t}"
+	for t in "${target_input}"; do
+		if [ "${t}" == "*/*" ] || [ "${t}" == "*" ]; then echo -n "${available_targets} "
+		elif [[ " ${available_targets} " == *" ${t} "* ]]; then echo -n "${t} "
 		elif [[ "${t}" == "*/"* ]]; then
-			local expanded=$(expand_target_prefix "${t:2}" "${available_sections}" "${available_archives}" )
-			local discovered="${discovered} ${expanded}"
+			local expanded=$(expand_target_prefix "${t:2}"])
+			echo -n "${expanded}"
 		elif [[ "${t}" == *"/*" ]]; then
-			local expanded=$(expand_target_suffix "${t:0:-2}" "${available_sections}" "${available_archives}" )
-			local discovered="${discovered} ${expanded}"
+			local expanded=$(expand_target_suffix "${t:0:-2}")
+			echo -n "${expanded}"
 		fi
 	done
-
-	echo "${discovered}" && return 0
+	
+	return 0
 }
 function expand_target_prefix() {
+	local available_archives="$(cd dists; ls -d * | tr '\n' ' ')"
 	local section="$1"
-	local available_sections="$2"
-	local available_archives="$3"
-	local expanded=""
 
-	[[ ! " ${available_sections} " == *" ${section} "* ]] || [ -z "${section}" ] \
-		&& echo "The specified section '${section}' does not exist." && exit 1
-	for archive in ${available_archives}; do expanded="${expanded} ${archive}/${section}"; done
+	[ -z "${section}" ] && echo "The specified section '${section}' does not exist." >&2 && return 1
+	for archive in ${available_archives}; do
+		[ ! -d "dists/${archive}/${section}" ] && \
+			echo "The specified section '${section}' does not exist." >&2 && return 1
+		echo -n "${archive}/${section} "
+	done
 
-	echo "${expanded}" && return 0
+	return 0
 }
 function expand_target_suffix() {
+	local available_sections="$(cd pool; ls -d * | tr '\n' ' ' )"
 	local archive="$1"
-	local available_sections="$2"
-	local available_archives="$3"
-	local expanded=""
 
-	[[ ! " ${available_archives} " == *" ${archive} "* ]] || [ -z "${archive}" ] \
-		&& echo "The specified archive '${archive}' does not exist." && exit 1
-	for section in ${available_sections}; do expanded="${expanded} ${archive}/${section}"; done
-
-	echo "${expanded}" && return 0
+	[ -z "${archive}" ] && echo "The specified archive '${archive}' does not exist." >&2 && return 1
+	for section in ${available_sections}; do
+		[ ! -d "dists/${archive}/${section}" ] && \
+			echo "The specified archive '${archive}' does not exist." >&2 && return 1
+		echo -n "${archive}/${section} "
+	done
+	
+	return 0
 }
+function index_packages() {
+	local package="$1"
+	local targets="$2"
 
-function gzip_and_bzip_file() {
-	local uncompressed_file = "$1"
-	gzip -c9 "${uncompressed_file}" > "${uncompressed_file}.gz"
-	bzip2 -c9 "${uncompressed_file}" > "${uncompressed_file}.bz2"
+	[ -n "${targets}" ] && echo "Targets: ${targets}"
+	[ -z "${targets}" ] && echo "There are no targets." >&2 && return 1
+
+	for t in ${targets}; do
+		local archive="${t%/*}"
+		local section="${t#*/}"
+		index_package "${package}" "${archive}" "${section}"
+	done
+
+	return 0
+}
+function index_package() {
+	local package="$1"
+	local archive="$2"
+	local section="$3"
+
+	# TODO: determine the package to add; it could be a:
+	# 1. native source package
+	# 2. non-native source package
+	# 3. native, architecture-specific, binary package, e.g. pkg_1.0.0-1ubuntu1~asdf_amd64.deb
+	# 4. non-native architecture-specific, binary package, e.g. pkg_1.0.0~asdf_i386.deb
+	# 5. native, architecture-independent, binary package, e.g. pkg_1.0.0~asdf_all.deb
+	# 6. non-native, architecture-independent, binary package, e.g. pkg_1.0.0-1ubuntu1~asdf_all.deb
+
+	# TODO: what characters are allowed in the version field of the filename? plus characters?
+
+
+	return 0
 }
 function discover_package() {
 	local package_path="$1"
-	package_extension="${package_path##*.}"
+	local package_extension="${package_path##*.}"
 
 	if [[ "${package_path}" == *"/*" ]]; then discover_package_directory "${package_path}"
 	elif [ "${package_extension}" == "deb" ]; then discover_binary_package "${package_path}"
 	elif [ "${package_extension}" == "dsc" ]; then discover_source_package "${package_path}"
-	else echo "Could not determine package contents." && return 1
+	else echo "Could not determine package contents; make sure it's a 'deb' or 'dsc' file." >&2 && return 1
 	fi
+
+	return 0
 }
 function discover_package_directory() {
 	return 0
@@ -94,30 +123,20 @@ function discover_binary_package() {
 	local package_filename="$(basename "${package_path}")"
 	return 0
 }
+function gzip_and_bzip_file() {
+	local uncompressed_file = "$1"
+	gzip -c9 "${uncompressed_file}" > "${uncompressed_file}.gz"
+	bzip2 -c9 "${uncompressed_file}" > "${uncompressed_file}.bz2"
+	return 0
+}
 
 assert_working_directory
-parse_arguments
-assert_arguments
-expanded_targets=$(expand_target "${target}" )
-
-[ -z "${expanded_targets}" ] && echo "None of the targets specified exit." && exit 1
-for p in ${expanded_targets}; do
-	[ ! -d "dists/${p}" ] && echo "The specified target ${p} does not exist." && exit 1
-	archive="${p%/*}"
-	section="${p#*/}"
-
-	# TODO: determine the package to add; it could be a:
-	# 1. native source package
-	# 2. non-native source package
-	# 3. native, architecture-specific, binary package, e.g. pkg_1.0.0-1ubuntu1~asdf_amd64.deb
-	# 4. non-native architecture-specific, binary package, e.g. pkg_1.0.0~asdf_i386.deb
-	# 5. native, architecture-independent, binary package, e.g. pkg_1.0.0~asdf_all.deb
-	# 6. non-native, architecture-independent, binary package, e.g. pkg_1.0.0-1ubuntu1~asdf_all.deb
-
-	# TODO: what characters are allowed in the file version? plus characters?
-done
-
+assert_arguments "${raw_target}" "${raw_package}"
+expanded_targets=$(expand_target "${raw_target}" )
+index_packages "${package}" "${expanded_targets}"
 exit 0
+
+##################################################################################################
 
 [ -z "$(ls "${package}" 2> /dev/null)" ] && echo "The package to add '${package}' could not be found." && exit 1
 filename="$(basename "${package}")"
